alias l='ls --color=auto -ACFrt'
alias ll='ls --color=auto -AFlrt'
alias db=distrobox
alias dbl="distrobox list"
alias dbe="distrobox enter"
alias dbr="distrobox rm --force"

export EDITOR=/usr/bin/vim
export VISUAL=/usr/bin/vim
export TZ=America/Los_Angeles
