project:
  type: website
  output-dir: ../docs

website:
  title: "Command Line Algorithmic Music System (CLAMS)"
  site-url: "https://algocompsynth.github.io/CLAMS/"
  description: "CLAMS Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

