---
title: "C Forth on the RP2350? Yes, Please!"
author: "M. Edward (Ed) Borasky"
institute: "Silicon Valley Forth Interest Group"
date: "2024-09-28"
editor: visual
format: 
  beamer:
    slide-level: 2
    theme: Montpellier
    aspectratio: 169
---

# A (Welcome) Surprise in the (E)mail

## August 8, 2024 - the Raspberry Pi Pico 2 is announced

-   [[*Raspberry Pi Pico 2, our new \$5 microcontroller board, on sale now*]{.underline}](https://www.raspberrypi.com/news/raspberry-pi-pico-2-our-new-5-microcontroller-board-on-sale-now/)
-   [[*Our RP2350 Partners made all this excellent stuff for you*]{.underline}](https://www.raspberrypi.com/news/our-rp2350-partners-made-all-this-excellent-stuff-for-you/)
-   [[*What’s new in Raspberry Pi Pico 2*]{.underline}](https://www.raspberrypi.com/news/whats-new-in-pico-2/)
-   [[*RP2350: the brains of Raspberry Pi Pico 2*]{.underline}](https://www.raspberrypi.com/news/rp2350-the-brains-of-raspberry-pi-pico-2/)

## Pico vs. Pico 2

|                    | Pico            | Pico 2          |
|--------------------|-----------------|-----------------|
| Processor          | RP2040          | RP2350          |
| On-chip SRAM       | 256 KiB + 8 KiB | 512 KiB + 8 KiB |
| Flash              | 2 MiB           | 4 MiB           |
| Price (Quantity 1) | \$4US           | \$5US           |

## RP2040 vs. RP2350

|                  | RP2040         | RP2350               |
|------------------|----------------|----------------------|
| CPU              | Arm Cortex M0+ | Arm Cortex M33       |
| Default clock    | 133 MHz        | 150 MHz              |
| Cores            | 2              | 2 \*                 |
| Integer divide   | co-processor   | machine instruction  |
| 32-bit floats    | software       | machine instructions |
| 64-bit floats    | software       | co-processor         |
| DSP instructions | no             | yes                  |
| PSRAM support    | no             | yes                  |

## About that \*

-   The RP2350 actually has four cores!

-   The two ARM Cortex M33 cores you know about, and

-   Two [[*RISC-V Hazard3*]{.underline}](https://github.com/Wren6991/Hazard3) cores

-   At boot time, you can boot up any two of the four cores.

## So I bought a few partner boards

-   [[*Pimoroni Pico Plus 2*]{.underline}](https://shop.pimoroni.com/products/pimoroni-pico-plus-2-w?variant=42182811942995)
    -   16 MiB flash, 8 MiB of PSRAM
-   [[*SparkFun Pro Micro - RP2350*]{.underline}](https://www.sparkfun.com/products/24870)
    -   16 MiB flash, 8 MiB of PSRAM
-   [[*iLabs Challenger+ RP2350 BConnect*]{.underline}](https://ilabs.se/challenger-rp2350-bconnect-datasheet/)
    -   8 MiB flash, 8 MiB PSRAM
-   [[*iLabs Challenger+ RP2350 WiFi6/BLE5*]{.underline}](https://ilabs.se/challenger-rp2350-wifi-ble/)
    -   8 MiB flash, 8 MiB PSRAM, WiFi and Bluetooth!

# The CLAMS Development Environment

## A collection of command-line Linux tools

-   [[*Raspberry Pi Pico-series C/C++ SDK*]{.underline}](https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-c-sdk.pdf)
-   [[*Raspberry Pi Pico Python SDK*]{.underline}](https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-python-sdk.pdf)
-   [[*CircuitPython*]{.underline}](https://circuitpython.org/)
-   [[*Arduino-Pico*]{.underline}](https://arduino-pico.readthedocs.io/en/latest/)
-   [[*PlatformIO Core (CLI)*]{.underline}](https://docs.platformio.org/en/latest/core/index.html)
-   Coming soon! [[*Zephyr*]{.underline}](https://docs.zephyrproject.org/latest/index.html)

## A container to run them in!

-   Many third parties have limited testing resources
-   If they support Linux at all, it's RHEL (expensive), or
-   Ubuntu 22.04 LTS aka "Jammy Jellyfish"
-   So I built a [[*Distrobox*]{.underline}](https://distrobox.it/) container running Ubuntu 22.04 LTS
-   Hosted on [[*Universal Blue Bluefin*]{.underline}](https://projectbluefin.io/)
-   (But any Distrobox host will work - any recent Linux distro)

# C Forth [[*https://github.com/MitchBradley/cforth*]{.underline}](https://github.com/MitchBradley/cforth)

## Why C Forth?

-   Optimized for microcontrollers
-   Comprehensive - derived from Mitch Bradley's Open FirmWare
-   Extensible in either C or Forth!
-   Portable - I want to run Forth on other microcontrollers
-   Linux build process is straightforward using PlatformIO

## Demo

# Questions?

My email: [*znmeb\@algocompsynth.com*]{.underline}
