---
title: "CLAMS-Forth for Forth Nerds"
author: "M. Edward (Ed) Borasky"
format:
  beamer:
    theme: "Montpellier"
    incremental: false
    slide_level: 2
bibliography: ../The-Book-of-CLAMS/references.bib
---

# The Prime Directives

## Forth 2012 compatibility?
- Extended subject of Forth 2012 [@forth2022] standard
- Not all CORE words implemented
- Some non-standard word sets implemented
- But ... 
    * CLAMS-Forth words ***in*** Forth 2012 work the same way.

## Run on a Raspberry Pi Pico WH
- Documentation: [@raspberrypi2023b]
- RP2040 CPU: Dual-core Arm Cortex M0+ with 264 KiB of SRAM
- Co-processors for division and digital signal processing
- I/O state machine (PIO) and ***oodles*** of real-world connectivity
- 2 MiB of flash
- 2.4 GHz WiFi / Bluetooth
- $7US with debug connector / headers for breadboarding
- Dozens of compatible devices!

## Initial target device: Pimoroni PicoVision
- Documentation: [@pimoroni2023a]
- Raspberry Pi Pico W
- "GPU" - an overclocked RP2040
- I2S audio output
- HDMI output
- MicroSD card
- USB
- ~ $37US

## Premature optimizations / extensions
- Dictionary split between RAM and flash
- Subroutine threading / inline compiling / assembly
- Engine in assembly
- Top of stack / stack pointer in registers
- Engine in assembly
- Support multiprocessing, multitasking, and halfword arithmetic
- High-performance vector block floating point DSP library

## Build with Raspberry Pi Pico C/C++ SDK
- Documentation:  [@raspberrypi2023a]
- Reference: [@smith2021rp2040]
- Why require Pico SDK?

## Why?

Because coding libraries / drivers are ***each*** multi-month projects in ASM / Forth!

- USB
- WiFi / Bluetooth
- I2S audio / HDMI
- SD card
- FreeRTOS

# Project status / road map

## Rough schedule

- 2023-11-17: Most of the inner interpreter is done
- Text interpreter should be done November 24
- Basic colon compiler should be done December 1
- I2S audio / HDMI should be done December 8
- Spend the rest of 2023 building PicoVision demos!!

# Implementation Details

## Workflow

## Languages

## The Forth virtual machine

## The dictionary

## The terminal and USB serial I/O

## I2S audio output

## HDMI video output

## References {.smaller}
