project:
  type: book
  output-dir: ../docs

book:
  title: "The Book of CLAMS"
  author: "M. Edward (Ed) Borasky"
  date: "12/15/2023"
  chapters:
    - index.qmd
    - About-My-Music.qmd
    - CLAMS-Forth-Overview.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: darkly
  pdf:
    documentclass: scrreprt



