# About My Music

> "Markovs of the world unite! You have nothing to lose but your chains!"
\~ M. Edward (Ed) Borasky

## AlgoCompSynth
"AlgoCompSynth" is a word I made up to describe what it is that I want to do.
It's a compression of "algorithmic composition and digital sound synthesis."
That's a pretty broad class of music; to narrow it down, the following are my
main inspirations.

- Iannis Xenakis' _Formalized Music_ [@xenakis1992formalized]. Xenakis took the
applied mathematics of his day, for example, operations research and game
theory, and used these algorithms to create scores for conventional and
electronic performers. He also invented a technique called "Dynamic
Stochastic Synthesis", which uses Markov processes to specify not just the
score of a piece but the parameters of the sound waveforms
[@hoffmann1996implementing; @brown2005extending; @xenakis1992formalized].

- Alternate tunings. Primary among these is William Sethares' _Tuning, Timbre
Spectrum, Scale_ [@sethares1998tuning; @sethares2013tuning]. Also influential:
Wendy Carlos [@carlos1987tuning], Harry Partch [@partch1979genesis], Erv
Wilson [@narushima2019microtonality] and Nick Collins [@collins2008errant;
@collins2012even].

- Physical modeling synthesis. A comprehensive reference can be found at
[@paspweb2010].

- Spectral music. This is another advanced synthesis methodology; a recent
reference is [@lazzarini2021spectral]

## Examples
My current home for published music is on Bandcamp at
<https://algocompsynth.bandcamp.com/>. The test case for CLAMS is a work in
progress called "A Musical Clambake", submitted as a proposal to the
[Hybrid Live Coding Interfaces Workshop
2023](https://hybrid-livecode.pubpub.org/workshop2023):

> "A Musical Clambake": A five minute algorithmic microtonal video produced
on a Pimoroni PicoVision
(https://shop.pimoroni.com/products/picovision?variant=41048911904851) using
the CLAMS (https://algocompsynth.github.io/CLAMS) live coding system. "A
Musical Clambake" revisits the birth of live coding, made possible by
inexpensive personal computers and the Forth programming language, and
explores what happens when the computer is a musical collaborator via dynamic
stochastic synthesis.

I am also planning to submit "A Musical Clambake" to the [Pimoroni PicoVision
Demoscene
Competition](https://shop.pimoroni.com/pages/win-a-500-gift-card-in-our-picovision-competition).

## Other AlgoCompSynth projects

1. [AlgoCompSynth-One](https://github.com/AlgoCompSynth/AlgoCompSynth-One):
This is a platform for doing high-performance digital signal processing and
musical AI on NVIDIA GPUs. I currently support Windows 11 WSL Ubuntu 22.04 LTS
and NVIDIA Jetson JetPack 5. If I can make everything work I will be
supporting native Windows 11.

2. [eikosany](https://algocompsynth.github.io/eikosany/): This is an R
package for algorithmic composition with musical scales derived by Erv Wilson
and students of his theories.

3. [consonaR](https://algocompsynth.github.io/consonaR/): This is an R
package to perform the computations described in _Tuning, Timbre, Spectrum,
Scale_ [@sethares2013tuning]. This is a superset of any such algorithms that
will be deployed in CLAMS; only calculations that need to be performed
during a performance need to be deployed in CLAMS.
