project:
  type: website
  output-dir: ../docs

website:
  title: "Command Line Algorithmic Music System (CLAMS)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
