project:
  type: website
  output-dir: ../docs

website:
  title: "Command Line Algorithmic Music System (CLAMS)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CLAMS-Design-Overview.qmd
    right: 
      - href: https://github.com/AlgoCompSynth/CLAMS
        text: "CLAMS on GitHub"
  body-footer: |
    <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://algocompsynth.github.io/CLAMS">Command Line Algorithmic Music System (CLAMS)</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://github.com/znmeb">M. Edward (Ed) Borasky</a> is licensed under <a href="http://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"></a></p>

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

