alias l='ls --color=auto -ACFrt'
alias ll='ls --color=auto -AFlrt'
alias install-p10k='source $HOME/powerlevel10k/powerlevel10k.zsh-theme'

export EDITOR=/usr/bin/vim
export VISUAL=/usr/bin/vim
export PATH=$PATH:$HOME/bin:$HOME/.local/bin
